# The Quake 2 port's fork of the bare-metal engine (from the taxi game's, in
# ../saturn-ctaxi/taxi/engine). Sourced by build.sh.
#   engine_build NAME "src files..." "extra CFLAGS"
# Produces game.elf, cd/0.bin, game.iso, game.cue in the project directory.
ENGINE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO="$(cd "$ENGINE/.." && pwd)"        # the toolchain (vendor/) and tools/
TC="$REPO/vendor/joengine/Compiler/LINUX/bin"
CC="$TC/sh-none-elf-gcc-8.2.0"
OBJCOPY="$TC/sh-none-elf-objcopy"

engine_build()
{
    local name="$1" srcs="$2" extra="$3" gen=obj/gen objs="" s o
    mkdir -p obj "$gen" cd
    python3 "$REPO/tools/dspasm.py" "$ENGINE/xform.dsp" "$gen/xform.h" xform_prog >/dev/null
    python3 "$REPO/tools/dspasm.py" "$ENGINE/xformb.dsp" "$gen/xformb.h" xformb_prog >/dev/null
    python3 "$REPO/tools/dspasm.py" "$ENGINE/xformp.dsp" "$gen/xformp.h" xformp_prog >/dev/null
    python3 "$REPO/tools/dspasm.py" "$ENGINE/xformm.dsp" "$gen/xformm.h" xformm_prog >/dev/null
    python3 "$REPO/tools/dspasm.py" "$ENGINE/xformf.dsp" "$gen/xformf.h" xformf_prog >/dev/null
    python3 - "$gen/sintab.h" <<'PY'
import math, sys
# a quarter of a wave: the rest by symmetry (the same values exactly), 4 KB not 16
v = [min(65536, round(math.sin(i * 2 * math.pi / 4096) * 65536)) for i in range(1025)]
with open(sys.argv[1], "w") as f:
    f.write("/* generated by engine/build.inc.sh: sin, 4096 steps per turn, 16.16; 0 to 1024 of them */\n")
    f.write("static const s32 sinq[1025] = {\n")
    for i in range(0, 1025, 12):
        f.write("    " + ", ".join(str(x) for x in v[i:i + 12]) + ",\n")
    f.write("};\n")
PY
    # the sound driver: on the 68000 (default), or the older SH-2 version (SOUND=sh2)
    local snd="$ENGINE/snd.c"
    if [ "${SOUND:-68k}" = sh2 ]; then
        snd="$ENGINE/snd_sh2.c"
    else
        local m68="m68k-linux-gnu" cf68="-m68000 -Os -ffreestanding -fno-builtin -nostdlib -fno-pic -fomit-frame-pointer -Wall -Wextra -Wno-unused-parameter"
        "$m68-gcc" $cf68 -c "$ENGINE/m68k/crt0.s" -o obj/m68k_crt0.o
        "$m68-gcc" $cf68 -c "$ENGINE/m68k/driver.c" -o obj/m68k_driver.o
        "$m68-gcc" $cf68 -c "$ENGINE/m68k/lib.c" -o obj/m68k_lib.o
        "$m68-ld" --no-warn-rwx-segments -T "$ENGINE/m68k/link.ld" -Map obj/m68k.map -o obj/m68k.elf obj/m68k_crt0.o obj/m68k_driver.o obj/m68k_lib.o
        "$m68-objcopy" -O binary obj/m68k.elf "$gen/snd68k.bin"
        # (its end, .bss and all, and 1 KB of stack below the sound bank at 0x2000: engine/snd68k.h)
        local drv_end
        drv_end=$(grep "__bss_end = \." obj/m68k.map | awk '{print $1}')
        if [ $((drv_end + 1024)) -gt $((0x2000)) ]; then
            echo "68000 driver too big for its space below the sound bank" >&2
            return 1
        fi
        cp "$gen/snd68k.bin" cd/SND68K.BIN     # (a file on the CD: not 4 KB of high work RAM)
    fi
    local cflags="-m2 -O2 -ffreestanding -fno-builtin -nostdlib -fno-common -Wall -Wextra -Wno-unused-parameter -I$ENGINE -I$gen -Isrc $extra"
    # the code's in high work RAM with the level's hottest data: what's rarely run is built
    # small (COLD: file names), leaving that room to the level
    local cold=" ${COLD:-} "
    for s in "$ENGINE/crt0.s" "$ENGINE/sys.c" "$ENGINE/vdp.c" "$ENGINE/dsp.c" "$ENGINE/rotplane.c" "$ENGINE/sky.c" "$ENGINE/lzss.c" "$ENGINE/bup.c" "$ENGINE/cd.c" $snd $srcs; do
        o=obj/$(basename "${s%.*}").o
        case "$cold" in
            *" $(basename "$s") "*) "$CC" $cflags -Os -c "$s" -o "$o" ;;
            *) "$CC" $cflags -c "$s" -o "$o" ;;
        esac
        objs="$objs $o"
    done
    "$CC" -m2 -nostdlib -nostartfiles -T "$ENGINE/link.ld" -Wl,-Map,game.map -o game.elf $objs -lgcc
    "$OBJCOPY" -O binary game.elf cd/0.bin
    [ -f cd/ABS.TXT ] || printf '%s' "$name" > cd/ABS.TXT
    [ -f cd/BIB.TXT ] || printf '%s' "$name" > cd/BIB.TXT
    [ -f cd/CPY.TXT ] || printf '(c) 2026' > cd/CPY.TXT
    mkisofs -quiet -sysid "SEGA SATURN" -volid "$name" -volset "$name" -sectype 2352 \
        -publisher "HOMEBREW" -preparer "HOMEBREW" -appid "$name" \
        -abstract cd/ABS.TXT -copyright cd/CPY.TXT -biblio cd/BIB.TXT \
        -generic-boot "$REPO/vendor/joengine/Compiler/COMMON/IP.BIN" -full-iso9660-filenames -o game.iso cd
    printf 'FILE "game.iso" BINARY\n  TRACK 01 MODE1/2048\n    INDEX 01 00:00:00\n' > game.cue
    echo "built: $(pwd)/game.cue  ($(stat -c %s cd/0.bin) bytes)"
}
