#!/usr/bin/env python3
"""Bake every model in tools/models.txt that's out of date (tools/bake_md2.py), and write
obj/gen/q2models.h: MDL_<NAME> numbers and the files, in the list's order.

    tools/bake_models.py data/pak0.pak cd/
"""
import os
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def main():
    pak, out = sys.argv[1], sys.argv[2]
    rows = []
    for line in open(os.path.join(ROOT, "tools", "models.txt")):
        line = line.split("#")[0].split()
        if line:
            rows.append(line)
    me = [os.path.getmtime(os.path.join(ROOT, "tools", f)) for f in ("models.txt", "bake_md2.py", "bake_models.py")]
    for name, file, md2, skins, anims, *opts in rows:
        dst = os.path.join(out, file)
        if os.path.exists(dst) and os.path.getmtime(dst) > max(me):
            continue
        cmd = [sys.executable, os.path.join(ROOT, "tools", "bake_md2.py"), pak, md2, dst, "--skins=" + skins]
        if anims != "-":
            cmd.append("--anims=" + anims)
        cmd += ["--" + o for o in opts]
        subprocess.check_call(cmd)
    gen = os.path.join(ROOT, "obj", "gen")
    os.makedirs(gen, exist_ok=True)
    with open(os.path.join(gen, "q2models.h"), "w") as f:
        f.write("/* generated by tools/bake_models.py from tools/models.txt */\n#ifndef Q2MODELS_H\n#define Q2MODELS_H\n")
        for i, r in enumerate(rows):
            f.write("#define MDL_%-12s (%d)\n" % (r[0].upper(), i))
        f.write("#define MDL_COUNT        (%d)\n" % len(rows))
        f.write("#define MDL_FILES        %s\n#endif\n" % ", ".join('"%s"' % r[1] for r in rows))


if __name__ == "__main__":
    main()
