#!/usr/bin/env python3
"""Bake a Quake 2 map for the Saturn renderer.

    tools/bake_map.py data/pak0.pak maps/demo1.bsp cd/DEMO1.MAP [--res=2] [--preview=dir]

Every face is cut into a grid of cells, T x T texels of texture space, aligned
to the texture's repeat, so a whole cell is one VDP1 distorted sprite of a
shared tile. A cell the face only partly covers is drawn:
  - from the tile, with a range of its rows (srca/height), if the face covers
    whole rows of it (cut off at the top or bottom)
  - from the transposed tile, likewise, if it covers whole columns
  - otherwise from a variant: the tile cropped to what the face covers, with
    the uncovered texels transparent
Textures are 4bpp with a colour table (16 RGB entries, 0 = transparent) per
tile, so VDP1 Gouraud shading still works on them. Lighting: Quake's
lightmap, sampled at the grid's vertices, turned into Gouraud offsets.

Everything is big-endian for the SH-2. The layout matches src/level.h.
"""
import math
import os
import struct
import sys
from collections import defaultdict

from PIL import Image

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from q2data import Pak, Bsp, Wal, palette, SURF_SKY, SURF_NODRAW, SURF_WARP, SURF_TRANS33, SURF_TRANS66, SURF_FLOWING

T = 32                  # cell size in texels of texture space
EPS = 1e-4

# face flags (src/level.h)
FF_SKY, FF_WARP, FF_TRANS33, FF_TRANS66, FF_FLOWING, FF_NODRAW, FF_BACK, FF_LOD = 1, 2, 4, 8, 16, 32, 64, 128
TEX_TRANSPOSED = 0x8000
CELL_FULL = 0x8000          # a cell's tex: a whole tile; then its colour table, not ty0/th
CELL_EXACT = 0x4000         # a cropped cell that's exactly its grid cell (the face's edge is the grid's)
LOD_MIN = 12                # the faces with coarse grids: this many cells or more
# movers (src/q2.h)
MV_NONE, MV_STATIC, MV_DOOR, MV_PLAT, MV_BUTTON = 0, 1, 2, 3, 4
MF_START_OPEN, MF_PROXIMITY, MF_SHOOT = 1, 2, 4
# entity classes: numbered in this order (1 up); tools/bake_map.py writes obj/gen/q2classes.h for the C side
CLASSES = """
    monster_soldier_light monster_soldier monster_soldier_ss monster_infantry monster_gunner monster_berserk monster_tank
    item_health_small item_health item_health_large item_health_mega
    item_armor_shard item_armor_jacket item_armor_combat item_armor_body
    ammo_shells ammo_bullets ammo_grenades ammo_rockets ammo_cells ammo_slugs
    weapon_shotgun weapon_supershotgun weapon_machinegun weapon_chaingun weapon_grenadelauncher weapon_rocketlauncher
    item_quad item_adrenaline item_silencer item_invulnerability item_breather item_enviro item_power_shield
    key_blue_key
    trigger_once trigger_multiple trigger_relay trigger_always trigger_counter trigger_key func_timer
    target_explosion target_splash target_secret target_goal target_help target_changelevel target_speaker
    misc_explobox misc_deadsoldier path_corner point_combat info_player_start
    func_door func_button func_plat func_train func_wall func_explosive func_rotating func_door_rotating
    func_areaportal func_water misc_teleporter misc_teleporter_dest
""".split()
CLASS_IDS = {c: i + 1 for i, c in enumerate(CLASSES)}


def write_class_header(path):
    with open(path, "w") as f:
        f.write("/* generated by tools/bake_map.py: entity classes */\n#ifndef Q2CLASSES_H\n#define Q2CLASSES_H\n")
        for c, i in CLASS_IDS.items():
            f.write("#define C_%-28s (%d)\n" % (c.upper(), i))
        f.write("#define C_COUNT                        (%d)\n#endif\n" % (len(CLASS_IDS) + 1))


# spawn kinds (src/q2.h)
SPAWN_KINDS = {"monster_soldier_light": 1, "monster_soldier": 2, "monster_soldier_ss": 3, "monster_infantry": 4}


def fx(v):
    """16.16 fixed"""
    return int(round(v * 65536.0))


def clip(poly, a, axis, keep_ge):
    out = []
    n = len(poly)
    for i in range(n):
        p, q = poly[i], poly[(i + 1) % n]
        pin = p[axis] >= a - EPS if keep_ge else p[axis] <= a + EPS
        qin = q[axis] >= a - EPS if keep_ge else q[axis] <= a + EPS
        if pin:
            out.append(p)
        if pin != qin:
            t = (a - p[axis]) / (q[axis] - p[axis])
            out.append((p[0] + (q[0] - p[0]) * t, p[1] + (q[1] - p[1]) * t))
    return out


def area(poly):
    a = 0.0
    for i in range(len(poly)):
        p, q = poly[i], poly[(i + 1) % len(poly)]
        a += p[0] * q[1] - q[0] * p[1]
    return abs(a) / 2


def rgb555(c):
    r, g, b = c
    return 0x8000 | ((b >> 3) << 10) | ((g >> 3) << 5) | (r >> 3)


class Baker:
    def __init__(self, pak, bsp, res, bright):
        self.pak, self.bsp, self.res, self.bright = pak, bsp, res, bright
        self.T = T                              # a cell's side in texels of the texture (a coarse pass doubles it)
        self.lod_min = LOD_MIN
        self.N = T // res                       # stored texels per cell side
        self.pal = palette(pak)
        self.wals = {}
        self.tiles = {}                         # (tex, tx, ty) -> tile index
        self.tile_data = []                     # [(indices N*N, lut[16])]
        self.masks, self.mask_ids = [], {}      # the variants' masks: 16 rows of 16 bits (bit x of the crop's row y)
        self.textures = []                      # (kind, ...) -> texture table entries
        self.tex_ids = {}                       # key -> texture index
        self.stats = defaultdict(int)

    def wal(self, name):
        if name not in self.wals:
            w = Wal(self.pak.read("textures/%s.wal" % name))
            # an overall brightness (1 = Quake's)
            k = self.bright
            pal = [tuple(min(255, int(c * k)) for c in col) for col in self.pal]
            rgb = [pal[i] for i in w.pixels]
            w.rgb = rgb
            n = len(rgb)
            w.avg = tuple(sum(c[k] for c in rgb) / n for k in range(3))
            self.wals[name] = w
        return self.wals[name]

    # ---- tiles and their variants ----

    def tile(self, name, tx, ty):
        """a T x T texel window of a texture (wrapping), downsampled and quantised: its index"""
        key = (name, tx, ty, self.res)
        if key in self.tiles:
            return self.tiles[key]
        w = self.wal(name)
        N, r = self.N, self.res
        img = Image.new("RGB", (N, N))
        px = []
        for y in range(N):
            for x in range(N):
                acc = [0, 0, 0]
                for yy in range(r):
                    for xx in range(r):
                        c = w.rgb[((ty + y * r + yy) % w.h) * w.w + (tx + x * r + xx) % w.w]
                        acc[0] += c[0]
                        acc[1] += c[1]
                        acc[2] += c[2]
                px.append(tuple(a // (r * r) for a in acc))
        img.putdata(px)
        q = img.quantize(colors=15, method=Image.Quantize.MEDIANCUT, dither=Image.Dither.NONE)
        pal = (q.getpalette() + [0] * 45)[:45]
        idx = [i + 1 for i in q.getdata()]      # 0 is transparent
        lut = [0] + [rgb555((pal[i * 3], pal[i * 3 + 1], pal[i * 3 + 2])) for i in range(15)]
        self.tiles[key] = len(self.tile_data)
        self.tile_data.append((idx, lut))
        return self.tiles[key]

    def texture(self, key, make):
        if key not in self.tex_ids:
            self.tex_ids[key] = len(self.textures)
            self.textures.append(make())
        return self.tex_ids[key]

    # a texture: (tile, w, h, data, transposed, gen). gen 0: its data's in the file; 1, 2: made
    # from its tile's as it's uploaded (src/render.c tex_generate: transposed, quartered), the
    # record's offset the tile's: the pixels aren't stored again
    def tex_tile(self, t):
        N = self.N
        return self.texture(("tile", t), lambda: (t, N, N, self.tile_data[t][0], False, 0))

    def tex_transposed(self, t):
        N = self.N
        self.tex_tile(t)
        return self.texture(("tileT", t), lambda: (t, N, N, None, True, 1))

    def tex_variant(self, t, mask, x0, y0, w, h):
        """the tile cropped to (x0, y0, w, h), texels outside the mask transparent: made as it's
        uploaded (gen 3) from the tile and a mask, 16 rows of 16 bits (the crop's row y, bit x)"""
        N = self.N
        rows = tuple(sum(1 << x for x in range(w) if mask[(y0 + y) * N + x0 + x]) for y in range(h)) + (0,) * (16 - h)
        if rows not in self.mask_ids:
            self.mask_ids[rows] = len(self.masks)
            self.masks.append(rows)
        key = ("var", t, x0, y0, w, h, rows)
        self.tex_tile(t)
        return self.texture(key, lambda: (t, w, h, None, False, 3, (x0, y0, self.mask_ids[rows])))

    # ---- faces ----

    def face_axes(self, fi):
        """world point of texture coords (u, v) on the face's plane: P0 + u*A + v*B"""
        b = self.bsp
        f = b.faces[fi]
        ti = b.texinfo[f["texinfo"]]
        n, d, _ = b.planes[f["plane"]]
        S, Tv = ti["s"], ti["t"]
        m = [S[:3], Tv[:3], n]
        det = (m[0][0] * (m[1][1] * m[2][2] - m[1][2] * m[2][1])
               - m[0][1] * (m[1][0] * m[2][2] - m[1][2] * m[2][0])
               + m[0][2] * (m[1][0] * m[2][1] - m[1][1] * m[2][0]))
        if abs(det) < 1e-6:
            return None
        # inverse, column k = solution for unit vector k
        inv = [[0] * 3 for _ in range(3)]
        for i in range(3):
            for j in range(3):
                a = [[m[r][c] for c in range(3) if c != i] for r in range(3) if r != j]
                cof = a[0][0] * a[1][1] - a[0][1] * a[1][0]
                inv[i][j] = cof * (-1) ** (i + j) / det
        col = lambda k: [inv[r][k] for r in range(3)]
        A, B, C = col(0), col(1), col(2)
        # P(u, v) = inv * (u - s_off, v - t_off, d)
        P0 = [A[r] * -S[3] + B[r] * -Tv[3] + C[r] * d for r in range(3)]
        return P0, A, B

    def lightmap(self, fi, pts):
        """(sampler(u, v) -> (r, g, b) 0..255 or None)"""
        b = self.bsp
        f = b.faces[fi]
        if f["lightofs"] < 0 or f["styles"][0] == 255:
            return None
        mins = [math.floor(min(p[k] for p in pts) / 16) for k in range(2)]
        maxs = [math.ceil(max(p[k] for p in pts) / 16) for k in range(2)]
        w, h = maxs[0] - mins[0] + 1, maxs[1] - mins[1] + 1
        ofs = f["lightofs"]
        lm = b.lighting

        def sample(u, v):
            x = min(max((u / 16.0) - mins[0], 0.0), w - 1.0)
            y = min(max((v / 16.0) - mins[1], 0.0), h - 1.0)
            x0, y0 = int(x), int(y)
            x1, y1 = min(x0 + 1, w - 1), min(y0 + 1, h - 1)
            fx_, fy = x - x0, y - y0
            out = []
            for c in range(3):
                g = lambda xx, yy: lm[ofs + (yy * w + xx) * 3 + c]
                top = g(x0, y0) * (1 - fx_) + g(x1, y0) * fx_
                bot = g(x0, y1) * (1 - fx_) + g(x1, y1) * fx_
                out.append(top * (1 - fy) + bot * fy)
            return out
        return sample

    def gouraud(self, light, avg):
        """lightmap colour -> VDP1 Gouraud offset (5 bits a channel, 16 = unchanged).
        VDP1 adds (g - 16) to the texel. Quake 2's software renderer multiplies
        it by light / 128 (128 = as drawn); that's lifted here by a gamma of
        0.55, or most of base1 (median light 47) is close to black on a TV."""
        if light is None:
            return 0x8000 | (16 << 10) | (16 << 5) | 16
        g = []
        for c in range(3):
            f = (light[c] / 128.0) ** 0.55
            k = avg[c] / 8.0 * 1.25            # texel brightness the offset is sized for, 5-bit units
            g.append(max(0, min(31, int(round(16 + (f - 1.0) * k)))))
        return 0x8000 | (g[2] << 10) | (g[1] << 5) | g[0]

    def bake_face(self, fi):
        b = self.bsp
        f = b.faces[fi]
        ti = b.texinfo[f["texinfo"]]
        flags = 0
        if ti["flags"] & SURF_SKY:
            flags |= FF_SKY
        if ti["flags"] & SURF_WARP:
            flags |= FF_WARP
        if ti["flags"] & SURF_TRANS33:
            flags |= FF_TRANS33
        if ti["flags"] & SURF_TRANS66:
            flags |= FF_TRANS66
        if ti["flags"] & SURF_FLOWING:
            flags |= FF_FLOWING
        if ti["flags"] & SURF_NODRAW:
            flags |= FF_NODRAW
        if f["side"]:
            flags |= FF_BACK
        empty = {"flags": flags | FF_NODRAW, "plane": f["plane"], "origin": (0, 0, 0), "edges": (0, 0, 0, 0),
                 "du": (0, 0, 0), "dv": (0, 0, 0), "nu": 0, "nv": 0, "cells": [], "lights": []}
        if flags & (FF_SKY | FF_NODRAW):
            return empty
        axes = self.face_axes(fi)
        if axes is None:
            self.stats["degenerate"] += 1
            return empty
        P0, A, B = axes
        w = self.wal(ti["texture"])
        S, Tv = ti["s"], ti["t"]
        pts = [(sum(v[k] * S[k] for k in range(3)) + S[3], sum(v[k] * Tv[k] for k in range(3)) + Tv[3])
               for v in b.face_verts(fi)]
        u0 = math.floor(min(p[0] for p in pts) / self.T + EPS)
        u1 = math.ceil(max(p[0] for p in pts) / self.T - EPS)
        v0 = math.floor(min(p[1] for p in pts) / self.T + EPS)
        v1 = math.ceil(max(p[1] for p in pts) / self.T - EPS)
        nu, nv = max(u1 - u0, 1), max(v1 - v0, 1)
        if nu > 255 or nv > 255:
            self.stats["too big"] += 1
            return empty
        N, r = self.N, self.res
        cells = []
        for cv in range(v0, v0 + nv):
            for cu in range(u0, u0 + nu):
                cells.append(self.bake_cell(ti["texture"], w, pts, cu, cv))
        # the grid's outer lines go on the face's edges rather than the tiles': the first column
        # starts at eu0 (stored texels into its tile), the last ends at eu1, the rows likewise;
        # so a cell cropped only by the face's edge is exactly its grid cell (no corners to work out)
        ext = [None if c[0] == 0xFFFF else (0, N, 0, N) if c[0] == "full" else c[3:7] for c in cells]

        def edge(idx, k, pick, default):
            vals = [ext[i][k] for i in idx if ext[i]]
            return pick(vals) if vals else default
        eu0 = edge([j * nu for j in range(nv)], 0, min, 0)
        eu1 = edge([j * nu + nu - 1 for j in range(nv)], 1, max, N)
        ev0 = edge(range(nu), 2, min, 0)
        ev1 = edge(range((nv - 1) * nu, nv * nu), 3, max, N)
        us = [(u0 + i) * self.T for i in range(nu + 1)]
        vs = [(v0 + j) * self.T for j in range(nv + 1)]
        us[0] += eu0 * r
        us[nu] = (u0 + nu - 1) * self.T + eu1 * r
        vs[0] += ev0 * r
        vs[nv] = (v0 + nv - 1) * self.T + ev1 * r
        sample = self.lightmap(fi, pts)
        lights = []
        for j in range(nv + 1):
            for i in range(nu + 1):
                lights.append(self.gouraud(sample(us[i], vs[j]) if sample else None, w.avg))
        origin = [P0[k] + A[k] * us[0] + B[k] * vs[0] for k in range(3)]
        du = [A[k] * self.T for k in range(3)]
        dv = [B[k] * self.T for k in range(3)]
        return {"flags": flags, "plane": f["plane"], "origin": origin, "du": du, "dv": dv, "edges": (eu0, eu1, ev0, ev1),
                "nu": nu, "nv": nv, "cells": cells, "lights": lights, "start": (us[0], vs[0])}

    def bake_cell(self, name, w, pts, cu, cv):
        """(texture, ty0, th, u0, u1, v0, v1): crop in stored texels of the cell"""
        N, r = self.N, self.res
        poly = clip(pts, cu * self.T, 0, True)
        if poly:
            poly = clip(poly, (cu + 1) * self.T, 0, False)
        if poly:
            poly = clip(poly, cv * self.T, 1, True)
        if poly:
            poly = clip(poly, (cv + 1) * self.T, 1, False)
        if len(poly) < 3 or area(poly) < 0.5:
            self.stats["cells empty"] += 1
            return (0xFFFF, 0, 0, 0, 0, 0, 0)
        # the cell in stored texels
        loc = [((p[0] - cu * self.T) / r, (p[1] - cv * self.T) / r) for p in poly]
        # conservative coverage: a texel is in if the polygon overlaps it
        mask = bytearray(N * N)
        for y in range(N):
            band = clip(loc, y, 1, True)
            if band:
                band = clip(band, y + 1, 1, False)
            if len(band) < 3 and not band:
                continue
            if not band:
                continue
            xl = min(p[0] for p in band)
            xr = max(p[0] for p in band)
            if xr - xl < EPS and max(p[1] for p in band) - min(p[1] for p in band) < EPS:
                continue
            for x in range(max(0, int(math.floor(xl + 1e-3))), min(N, int(math.ceil(xr - 1e-3)))):
                mask[y * N + x] = 1
        if not any(mask):
            self.stats["cells empty"] += 1
            return (0xFFFF, 0, 0, 0, 0, 0, 0)
        t = self.tile(name, (cu * self.T) % w.w, (cv * self.T) % w.h)
        if all(mask):
            self.stats["cells full"] += 1
            return ("full", self.tex_tile(t), t)
        xs = [i % N for i in range(N * N) if mask[i]]
        ys = [i // N for i in range(N * N) if mask[i]]
        x0, x1, y0, y1 = min(xs), max(xs) + 1, min(ys), max(ys) + 1
        rect = sum(mask) == (x1 - x0) * (y1 - y0)
        if rect and x0 == 0 and x1 == N:
            self.stats["cells rows"] += 1
            return (self.tex_tile(t), y0, y1 - y0, 0, N, y0, y1)
        if rect and y0 == 0 and y1 == N:
            self.stats["cells columns"] += 1
            return (self.tex_transposed(t), x0, x1 - x0, x0, x1, 0, N)
        # a variant: width a multiple of 8
        wv = (x1 - x0 + 7) & ~7
        if x0 + wv > N:
            x0 = N - wv
        self.stats["cells variant"] += 1
        return (self.tex_variant(t, mask, x0, y0, wv, y1 - y0), 0, y1 - y0, x0, x0 + wv, y0, y1)

    # ---- output ----

    def bake(self, out_path, preview=None):
        b = self.bsp
        faces = [self.bake_face(fi) for fi in range(len(b.faces))]
        # far faces' coarse grids: 64-texel cells, the textures at half the resolution (the same
        # N stored texels a cell, so the same drawing); for the faces of LOD_MIN cells or more (the
        # big ones: most of the far cells, and the least edge, where the cells need their own
        # masked textures)
        lods = [None] * len(faces)
        self.T, self.res = 2 * T, 2 * self.res
        for fi, f in enumerate(faces):
            if f["flags"] & (FF_SKY | FF_NODRAW) or f["nu"] * f["nv"] < self.lod_min:
                continue
            lf = self.bake_face(fi)
            if lf["nu"] * lf["nv"] < f["nu"] * f["nv"] and not lf["flags"] & FF_NODRAW:
                f["lod"] = sum(1 for x in lods if x)     # its record's number (the records go in this order)
                lods[fi] = lf
                f["flags"] |= FF_LOD
        self.T, self.res = T, self.res // 2
        blob = Blob()
        lumps = {}
        datas = {}

        def lump(name, data):
            datas[name] = data

        lump("planes", b"".join(struct.pack(">4iBBH", fx(n[0]), fx(n[1]), fx(n[2]), fx(d), t,
                                            (n[0] < 0) | (n[1] < 0) << 1 | (n[2] < 0) << 2, 0)
                                for n, d, t in b.planes))
        lump("nodes", b"".join(struct.pack(">H2h2H6hH", n[0], n[1][0], n[1][1], n[4], n[5], *n[2], *n[3], 0)
                               for n in b.nodes))
        lump("leafs", b"".join(struct.pack(">2h6h4Hi", l["cluster"], l["area"], *l["mins"], *l["maxs"],
                                           l["firstface"], l["numfaces"], l["firstbrush"], l["numbrushes"],
                                           l["contents"]) for l in b.leafs))
        lump("marks", struct.pack(">%dH" % len(b.leaffaces), *b.leaffaces))
        def pack_cells(f, cdata):
            eu0, eu1, ev0, ev1 = f["edges"]
            nu = f["nu"]
            for k, c in enumerate(f["cells"]):
                if c[0] == "full":
                    # a whole tile (src/q2.h q_cell_fast): its colour table, all its rows
                    assert c[1] < CELL_EXACT
                    cdata.append(struct.pack(">2H4B", CELL_FULL | c[1], c[2], 0, 0, self.N >> 3, self.N))
                elif c[0] == 0xFFFF:
                    cdata.append(struct.pack(">H6B", *c))
                else:
                    i, j = k % nu, k // nu
                    edge = (eu0 if i == 0 else 0, eu1 if i == nu - 1 else self.N,
                            ev0 if j == 0 else 0, ev1 if j == f["nv"] - 1 else self.N)
                    assert c[0] < CELL_EXACT
                    if tuple(c[3:7]) == edge:
                        # cropped, but exactly its grid cell: as a whole tile's, with the texture's
                        # colour table (and whether it's transposed), where its rows start (in 8
                        # bytes), its width / 8 and how many rows (q_cell_fast)
                        lt, w, h, data, tr, gen = self.textures[c[0]][:6]
                        assert (c[1] * w) % 16 == 0
                        cdata.append(struct.pack(">2H4B", c[0] | CELL_EXACT, lt | (TEX_TRANSPOSED if tr else 0),
                                                 c[1], c[1] * w // 16, w >> 3, c[2]))
                    else:
                        cdata.append(struct.pack(">H6B", *c))

        fdata, cdata, ldata = [], [], []
        axes = {}
        ncells = nlights = 0
        for f in faces:
            eu0, eu1, ev0, ev1 = f["edges"]
            # the grid's axes: 575 pairs among 7,500 faces, so a table (in high work RAM)
            key = tuple(fx(x) for x in f["du"]) + tuple(fx(x) for x in f["dv"])
            if key not in axes:
                axes[key] = len(axes)
            lod = f.get("lod", 0)
            assert nlights < 1 << 24 and lod < 1 << 16
            fdata.append(struct.pack(">3iHHBBBBBBBBII", *[fx(x) for x in f["origin"]], axes[key], f["plane"],
                                     f["flags"], f["nu"], f["nv"], eu0, eu1, ev0, ev1, lod >> 8, ncells,
                                     (lod & 255) << 24 | nlights))
            pack_cells(f, cdata)
            ldata.append(struct.pack(">%dH" % len(f["lights"]), *f["lights"]))
            ncells += len(f["cells"])
            nlights += len(f["lights"])
        # the coarse grids (on the cart): a record a face (zeros for those without one), their cells
        # and lights. Its first point's a few texels from the face's along u and v (its texels are
        # twice the size, and masked cells widen to 8 of them differently)
        lfdata, lcdata, lldata = [], [], []
        nlc = nll = 0
        for fi, lf in enumerate(lods):
            if not lf:
                continue
            f = faces[fi]
            offu = round(f["start"][0] - lf["start"][0])
            offv = round(f["start"][1] - lf["start"][1])
            assert -128 <= offu < 128 and -128 <= offv < 128, (offu, offv)
            lfdata.append(struct.pack(">6B2bII", lf["nu"], lf["nv"], *lf["edges"], offu, offv, nlc, nll))
            pack_cells(lf, lcdata)
            lldata.append(struct.pack(">%dH" % len(lf["lights"]), *lf["lights"]))
            nlc += len(lf["cells"])
            nll += len(lf["lights"])
        lump("lodfaces", b"".join(lfdata))
        lump("lodcells", b"".join(lcdata))
        lump("lodlights", b"".join(lldata))
        lump("faces", b"".join(fdata))                          # 32 bytes a face
        lump("axes", b"".join(struct.pack(">6i", *k) for k in axes))
        lump("cells", b"".join(cdata))                          # 8 bytes a cell
        lump("lights", b"".join(ldata))
        # every tile quartered: its four N/2 x N/2 quarters one under another (top left, top right,
        # bottom left, bottom right), for a whole tile too near the camera to draw in one piece
        # (src/render.c cell_split); quarter q of tile t is texture quart0 + t, from row q * N/2
        N, h = self.N, self.N // 2
        for t in range(len(self.tile_data)):
            self.tex_tile(t)                # (every tile's own texture: the quartered one's made from it)
        quart0 = len(self.textures)
        for t in range(len(self.tile_data)):
            self.texture(("quart", t), lambda t=t: (t, h, N * 2, None, False, 2))
        lump("quarts", struct.pack(">I", quart0))
        # textures: 4bpp, rows of w/2 bytes; each starts on 8 bytes (srca). One made as it's
        # uploaded (src/render.c tex_make) has how in the top bits of its offset (TEX_GEN_SHIFT:
        # 1 transposed, 2 quartered, 3 a masked crop: its mask's number, y0, x0 below) and its
        # tile from its colour table's number (tileofs: each tile's offset)
        tex_table, tex_blob, offs = [], bytearray(), {}
        for i, tex in enumerate(self.textures):
            t, w, h, data, transposed, gen = tex[:6]
            if gen:
                continue
            offs[i] = len(tex_blob)
            for k in range(0, len(data), 2):
                tex_blob.append((data[k] << 4) | data[k + 1])
            while len(tex_blob) & 31:
                tex_blob.append(0)
        for i, tex in enumerate(self.textures):
            t, w, h, data, transposed, gen = tex[:6]
            if gen == 3:
                x0, y0, mid = tex[6]
                assert mid < 65536 and x0 < 16 and y0 < 16
                ofs = (3 << 28) | (mid << 12) | (y0 << 8) | (x0 << 4)
            elif gen:
                ofs = gen << 28
            else:
                ofs = offs[i]
            tex_table.append(struct.pack(">IHBB", ofs, t | (TEX_TRANSPOSED if transposed else 0), w, h))
        lump("tileofs", struct.pack(">%dI" % len(self.tile_data), *[offs[self.tex_ids[("tile", t)]] for t in range(len(self.tile_data))]))
        lump("masks", b"".join(struct.pack(">16H", *rows) for rows in self.masks))
        print("  textures: %d, %d made as uploaded (%d masks)" % (len(self.textures),
              sum(1 for tex in self.textures if tex[5]), len(self.masks)))
        lump("textures", b"".join(tex_table))
        lump("texdata", bytes(tex_blob))
        lump("luts", b"".join(struct.pack(">16H", *lut) for _, lut in self.tile_data))
        # visibility: cluster count, then per cluster the PVS offset (into this lump), then the rows
        vis = b.raw["visibility"]
        if vis:
            # Quake's offsets count from the lump's start; the header keeps its size (4 + 8 a cluster),
            # so they still hold once the integers are byte-swapped
            nc = b.numclusters
            body = vis[4 + 8 * nc:]
            hdr = struct.pack(">I", nc) + b"".join(struct.pack(">2I", o[0], o[1]) for o in b.visofs)
            lump("vis", hdr + body)
        else:
            lump("vis", struct.pack(">I", 0))
        lump("models", b"".join(struct.pack(">9i3i", *[fx(x) for x in m["mins"]], *[fx(x) for x in m["maxs"]],
                                            *[fx(x) for x in m["origin"]], m["headnode"], m["firstface"],
                                            m["numfaces"]) for m in b.models))
        # the player start
        start, angle = (0, 0, 0), 0
        for e in b.parse_entities():
            if e.get("classname") == "info_player_start":
                start = tuple(float(x) for x in e["origin"].split())
                angle = float(e.get("angle", 0))
                if "targetname" not in e:
                    break
        lump("start", struct.pack(">4i", fx(start[0]), fx(start[1]), fx(start[2]), fx(angle)))
        # every start, by name (another level's exit names the one you arrive at: "demo2$base1")
        starts = []
        for e in b.parse_entities():
            if e.get("classname") == "info_player_start":
                o = [float(x) for x in e["origin"].split()]
                starts.append(struct.pack(">16s4i", e.get("targetname", "").encode("latin-1")[:15],
                                          fx(o[0]), fx(o[1]), fx(o[2]), fx(float(e.get("angle", 0)))))
        lump("starts", b"".join(starts))
        movers = self.movers()
        lump("movers", b"".join(movers))
        self.sky(out_path[:-4] + ".SKY")
        lump("sky", b"")                    # (its own file now: the game reads it straight into VDP2)
        spawns = self.spawns()
        lump("spawns", b"".join(spawns))
        erecs, estrings = self.entities()
        lump("entities2", b"".join(erecs))
        lump("strings", estrings)
        lump("leaflight", self.leaf_light(faces))
        # which faces each cluster can really see (tools/facevis.c): Quake's run-length zeros, per
        # cluster an offset then the rows
        rows = self.facevis(self.facevis_setting)
        offs, body = [], bytearray()
        for r in rows:
            offs.append(len(body))
            body += rle_zeros(r)
        hdr = 4 + 4 * len(rows)
        lump("facevis", struct.pack(">I", len(rows)) + b"".join(struct.pack(">I", hdr + o) for o in offs) + bytes(body))

        # collision: brushes (contents, sides), their sides (plane, surface flags), the leaves' brush lists
        lump("brushes", b"".join(struct.pack(">i2H", br["contents"], br["firstside"], br["numsides"])
                                 for br in b.brushes))
        lump("brushsides", b"".join(struct.pack(">2H", bs["plane"],
                                                b.texinfo[bs["texinfo"]]["flags"] & 0xFFFF if bs["texinfo"] >= 0 else 0)
                                    for bs in b.brushsides))
        lump("leafbrushes", struct.pack(">%dH" % len(b.leafbrushes), *b.leafbrushes))

        # the portals between clusters (a box each), and each cluster's list of them (a first index a
        # cluster, one more at the end, then the other cluster and the portal's number, each of them)
        portals = self.cluster_portals() if self.portals else []
        lump("portals", b"".join(struct.pack(">6h", *lo, *hi) for ka, kc, lo, hi in portals))
        per = [[] for _ in range(b.numclusters)]
        for i, (ka, kc, _, _) in enumerate(portals):
            per[ka].append((kc, i))
            per[kc].append((ka, i))
        first, lst = [], []
        for c in range(b.numclusters):
            first.append(len(lst) // 2)
            for o, i in per[c]:
                lst += [o, i]
        first.append(len(lst) // 2)
        lump("cportals", struct.pack(">%dH" % len(first), *first) + struct.pack(">%dH" % len(lst), *lst)
             if portals else b"")
        order = ["planes", "nodes", "leafs", "marks", "faces", "cells", "lights", "textures", "texdata", "luts",
                 "vis", "models", "start", "brushes", "brushsides", "leafbrushes", "movers", "facevis", "sky", "spawns",
                 "leaflight", "entities2", "strings", "axes", "quarts", "lodfaces", "lodcells", "lodlights", "starts", "portals", "cportals",
                 "tileofs", "masks"]
        counts = {"planes": len(b.planes), "nodes": len(b.nodes), "leafs": len(b.leafs), "marks": len(b.leaffaces),
                  "faces": len(faces), "cells": ncells, "lights": nlights, "textures": len(self.textures),
                  "texdata": len(tex_blob), "luts": len(self.tile_data), "vis": b.numclusters,
                  "models": len(b.models), "start": 1, "brushes": len(b.brushes),
                  "brushsides": len(b.brushsides), "leafbrushes": len(b.leafbrushes), "movers": len(movers),
                  "facevis": len(rows), "sky": 0, "spawns": len(spawns), "leaflight": len(b.leafs),
                  "entities2": len(erecs), "strings": len(estrings), "axes": len(axes),
                  "quarts": len(self.tile_data), "lodfaces": len(lods), "lodcells": nlc, "lodlights": nll,
                  "starts": len(starts), "portals": len(portals), "cportals": len(portals) and len(first),
                  "tileofs": len(self.tile_data), "masks": len(self.masks)}
        # the file: what the game reads off the cart first, then TAIL, in its order: what it copies
        # to work RAM as the level loads (src/level.c), and gives back to the cart from the first
        # of those it copied to the end (the most likely to fit last)
        for n in [n for n in datas if n not in TAIL] + TAIL:
            lumps[n] = blob.add(datas[n])
        hsize = (12 + 8 * len(order) + 31) & ~31
        final = bytearray(b"Q2SL" + struct.pack(">IHH", 1, T, self.N))
        for n in order:
            final += struct.pack(">II", lumps[n] + hsize, counts[n])
        final = bytes(final).ljust(hsize, b"\0") + blob.data()
        with open(out_path, "wb") as fo:
            fo.write(final)

        s = self.stats
        print("%s: %d faces, %d cells (full %d, rows %d, columns %d, variants %d, empty %d), %d tiles, %d textures"
              % (out_path, len(faces), ncells, s["cells full"], s["cells rows"], s["cells columns"],
                 s["cells variant"], s["cells empty"], len(self.tile_data), len(self.textures)))
        print("  " + " ".join("%s %dK" % (n, blob.sizes[lumps[n]] // 1024) for n in order) + "  total %dK" % (len(final) // 1024))
        if s["degenerate"] or s["too big"]:
            print("  skipped: %d degenerate, %d too big" % (s["degenerate"], s["too big"]))
        if preview:
            self.preview(preview)

    def name_id(self, n):
        """targetnames, targets, teams...: one numbering for everything (0 = none)"""
        if not n:
            return 0
        if not hasattr(self, "names"):
            self.names = {}
        if n not in self.names:
            self.names[n] = len(self.names) + 1
        return self.names[n]

    def entities(self):
        """Every entity the game might use, as fixed records (src/game.h q_erec), and their
        strings. Keys it doesn't have are UNSET (the game supplies Quake's defaults)."""
        UNSET = -0x80000000
        recs, strings = [], bytearray(b"\0")
        for e in self.bsp.parse_entities():
            cls = e.get("classname", "")
            if cls not in CLASS_IDS:
                continue

            def num(k):
                return fx(float(e[k])) if k in e else UNSET

            def ival(k, d=0):
                return int(float(e[k])) if k in e else d
            msg = 0
            if "message" in e or "map" in e:
                msg = len(strings)
                strings += (e.get("message") or e.get("map")).replace("\\n", "\n").encode("latin-1") + b"\0"
            o = [float(x) for x in e.get("origin", "0 0 0").split()]
            a = float(e.get("angle", 0))
            ang = 0xFFFF if a == -1 else 0xFFFE if a == -2 else int(round(a * 65536 / 360)) & 0xFFFF
            model = int(e["model"][1:]) if e.get("model", "").startswith("*") else 0
            recs.append(struct.pack(">6H3i2H4i4h2H2H", CLASS_IDS[cls], model, self.name_id(e.get("targetname")),
                                    self.name_id(e.get("target")), self.name_id(e.get("killtarget")), msg,
                                    *[fx(x) for x in o], ang, ival("spawnflags") & 0xFFFF,
                                    num("delay"), num("wait"), num("random"), num("speed"),
                                    ival("dmg"), ival("health"), ival("count"), ival("style"),
                                    self.name_id(e.get("pathtarget")), self.name_id(e.get("team")),
                                    CLASS_IDS.get(e.get("item"), 0), 0))
        return recs, bytes(strings)

    def spawns(self):
        """monsters and the like: kind, angle (16-bit), spawnflags, origin (16.16). Layout: src/q2.h q_spawn"""
        out = []
        for e in self.bsp.parse_entities():
            k = SPAWN_KINDS.get(e.get("classname"))
            if k is None or "origin" not in e:
                continue
            o = [float(x) for x in e["origin"].split()]
            a = int(round(float(e.get("angle", 0)) * 65536 / 360)) & 0xFFFF
            out.append(struct.pack(">HHI3i", k, a, int(e.get("spawnflags", 0)), *[fx(x) for x in o]))
        return out

    def leaf_light(self, faces):
        """per leaf, the light for models in it: the mean of its faces' lightmap samples, as a
        brightness per channel (8.8, 1.0 = as drawn: Quake's light / 128, gamma-lifted like the walls)"""
        b = self.bsp
        out = bytearray()
        for l in b.leafs:
            acc = [0.0, 0.0, 0.0]
            n = 0
            for fi in b.leaffaces[l["firstface"]:l["firstface"] + l["numfaces"]]:
                f = b.faces[fi]
                if f["lightofs"] < 0 or f["styles"][0] == 255:
                    continue
                lm = b.lighting
                o = f["lightofs"]
                # a handful of the face's samples
                for k in range(0, 48, 3):
                    if o + k + 2 < len(lm):
                        for c in range(3):
                            acc[c] += lm[o + k + c]
                        n += 1
            if n:
                col = [((acc[c] / n) / 128.0) ** 0.55 for c in range(3)]
            else:
                col = [0.8, 0.8, 0.8]
            out += struct.pack(">3H", *[min(0xFFFF, int(c * 256)) for c in col])
            out += b"\0\0"
        return bytes(out)

    def sky(self, out_path):
        """The skybox (the level's "sky", unit1_ if none) as a VDP2 layer: tools/bake_sky.py, beside
        the level (cd/DEMO1.SKY)"""
        import bake_sky
        name = self.bsp.parse_entities()[0].get("sky", "unit1_")
        bake_sky.bake(self.pak, name, out_path)

    def cluster_portals(self):
        """The openings between clusters: qbsp's portals made again (tools/portal_estimate.py), a
        box each (whole units, a unit out all round), merged per pair of clusters; for the
        renderer's flow (src/render.c portals_flow). Cached in obj/ by the map's hash."""
        import hashlib
        b = self.bsp
        root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
        h = hashlib.sha1()
        for name in ("planes", "nodes", "leafs"):
            h.update(b.raw[name])
        h.update(repr((b.models[0]["headnode"], b.models[0]["mins"], b.models[0]["maxs"])).encode())
        cache = os.path.join(root, "obj", "portals_%s.bin" % h.hexdigest()[:16])
        if not os.path.exists(cache):
            import portal_estimate as pe
            print("  portals: making the BSP's again (a minute or two)...")
            leaves = pe.make_portals(b)
            cp, seen = {}, set()
            for l in leaves:
                for pt in l.portals:
                    if id(pt) in seen:
                        continue
                    seen.add(id(pt))
                    a, c = pt.nodes
                    if a.leaf is None or c.leaf is None or a.leaf < 0 or c.leaf < 0 or (a.contents | c.contents) & 1:
                        continue
                    ka, kc = b.leafs[a.leaf]["cluster"], b.leafs[c.leaf]["cluster"]
                    if ka == kc or ka < 0 or kc < 0:
                        continue
                    k = (min(ka, kc), max(ka, kc))
                    lo = [int(math.floor(min(q[i] for q in pt.w))) - 1 for i in range(3)]
                    hi = [int(math.ceil(max(q[i] for q in pt.w))) + 1 for i in range(3)]
                    if k in cp:
                        o = cp[k]
                        cp[k] = ([min(o[0][i], lo[i]) for i in range(3)], [max(o[1][i], hi[i]) for i in range(3)])
                    else:
                        cp[k] = (lo, hi)
            with open(cache, "wb") as fo:
                for (ka, kc), (lo, hi) in sorted(cp.items()):
                    fo.write(struct.pack("<2H6h", ka, kc, *lo, *hi))
        data = open(cache, "rb").read()
        return [(r[0], r[1], r[2:5], r[5:8]) for r in struct.iter_unpack("<2H6h", data)]

    def facevis(self, setting="24", res=128):
        """per cluster, a bit per face: can it be seen from anywhere in the cluster
        (tools/facevis.c renders from sample points: each leaf's middle, random ones, and with a
        "c" its corners: --facevis=24, 64c, ...). Cached in obj/ by the map's hash and the tool's."""
        samples = int(setting.rstrip("c")) | (0x10000 if setting.endswith("c") else 0)
        import hashlib
        import subprocess
        b = self.bsp
        root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
        tool = os.path.join(root, "obj", "facevis")
        src = os.path.join(root, "tools", "facevis.c")
        os.makedirs(os.path.join(root, "obj"), exist_ok=True)
        if not os.path.exists(tool) or os.path.getmtime(tool) < os.path.getmtime(src):
            subprocess.check_call(["cc", "-O2", "-o", tool, src, "-lm"])
        blob = bytearray(struct.pack("<6i", len(b.faces), len(b.leafs), len(b.nodes), b.numclusters, samples, res))
        for fi, f in enumerate(b.faces):
            ti = b.texinfo[f["texinfo"]]
            n, d, _ = b.planes[f["plane"]]
            if f["side"]:
                n, d = tuple(-x for x in n), -d
            verts = b.face_verts(fi)
            occ = 0 if ti["flags"] & (SURF_TRANS33 | SURF_TRANS66 | SURF_NODRAW) else 1
            blob += struct.pack("<2i4f", len(verts), occ | 2, *n, d)
            for v in verts:
                blob += struct.pack("<3f", *v)
        for l in b.leafs:
            fl = b.leaffaces[l["firstface"]:l["firstface"] + l["numfaces"]]
            blob += struct.pack("<2i6fi", l["cluster"], l["contents"], *l["mins"], *l["maxs"], len(fl))
            blob += struct.pack("<%di" % len(fl), *fl)
        for n in b.nodes:
            pn, pd, _ = b.planes[n[0]]
            blob += struct.pack("<4f2i", *pn, pd, n[1][0], n[1][1])
        for c in range(b.numclusters):
            blob += b.pvs(c)
        key = hashlib.sha1(bytes(blob) + open(src, "rb").read()).hexdigest()[:16]
        cache = os.path.join(root, "obj", "facevis_%s.bin" % key)
        if not os.path.exists(cache):
            inp = cache + ".in"
            with open(inp, "wb") as fo:
                fo.write(blob)
            print("  facevis: rendering from %s samples a cluster (minutes)..." % setting)
            subprocess.check_call([tool, inp, cache])
            # (how good: new random points, 2 a cluster: what they see that their cluster doesn't list)
            print("  facevis " + subprocess.run([tool, inp, cache, "--check", "2"], capture_output=True,
                                                text=True).stdout.strip())
            os.remove(inp)
        data = open(cache, "rb").read()
        row = (len(b.faces) + 7) // 8
        rows = [data[c * row:(c + 1) * row] for c in range(b.numclusters)]
        pvs_faces = seen = 0
        for c in range(0, b.numclusters, 7):
            seen += sum(bin(x).count("1") for x in rows[c])
            pv = b.pvs(c)
            ok = set()
            for l in b.leafs:
                lc = l["cluster"]
                if lc >= 0 and pv[lc >> 3] & (1 << (lc & 7)):
                    ok.update(b.leaffaces[l["firstface"]:l["firstface"] + l["numfaces"]])
            pvs_faces += len(ok)
        print("  facevis: %.0f%% of the PVS's faces are really visible" % (100.0 * seen / max(pvs_faces, 1)))
        return rows

    def movers(self):
        """One record per brush model (index = model number): what it is and how it
        moves, from its entity (Quake 2's game/g_func.c spawn functions).
        Layout: src/q2.h q_mover."""
        b = self.bsp
        ents = {}
        for e in b.parse_entities():
            if e.get("model", "").startswith("*"):
                ents[int(e["model"][1:])] = e
        name_id = self.name_id

        def movedir(e):
            a = float(e.get("angle", 0))
            if a == -1:
                return (0.0, 0.0, 1.0)
            if a == -2:
                return (0.0, 0.0, -1.0)
            r = math.radians(a)
            return (round(math.cos(r), 6), round(math.sin(r), 6), 0.0)

        recs = []
        teams = {}
        info = []
        for mi in range(len(b.models)):
            m = b.models[mi]
            e = ents.get(mi, {})
            cls = e.get("classname", "worldspawn" if mi == 0 else "")
            size = [m["maxs"][k] - m["mins"][k] for k in range(3)]
            kind, move, speed, wait, flags = MV_NONE, (0.0, 0.0, 0.0), 0.0, 0.0, 0
            tmin, tmax = m["mins"], m["maxs"]
            spawnflags = int(e.get("spawnflags", 0))
            if cls == "func_door":
                kind = MV_DOOR
                d = movedir(e)
                lip = float(e.get("lip", 8))
                dist = sum(abs(d[k]) * size[k] for k in range(3)) - lip
                move = tuple(d[k] * dist for k in range(3))
                speed = float(e.get("speed", 100))
                wait = float(e.get("wait", 3))
                if spawnflags & 1:
                    flags |= MF_START_OPEN
                if "targetname" not in e and "health" not in e:
                    flags |= MF_PROXIMITY
            elif cls == "func_plat":
                kind = MV_PLAT
                lip = float(e.get("lip", 8))
                h = float(e["height"]) if "height" in e else size[2] - lip
                move = (0.0, 0.0, -h)
                speed = float(e["speed"]) if "speed" in e else 200.0
                wait = 3.0
                tmax = [m["maxs"][0] - 25, m["maxs"][1] - 25, m["maxs"][2] + 8]
                tmin = [m["mins"][0] + 25, m["mins"][1] + 25, tmax[2] - (h + lip)]
                if spawnflags & 1:
                    tmax[2] = tmin[2] + 8
                for k in range(2):
                    if tmax[k] - tmin[k] <= 0:
                        tmin[k] = (m["mins"][k] + m["maxs"][k]) * 0.5
                        tmax[k] = tmin[k] + 1
                if "targetname" not in e:
                    flags |= MF_START_OPEN          # it starts at the bottom
            elif cls == "func_button":
                kind = MV_BUTTON
                d = movedir(e)
                lip = float(e.get("lip", 4))
                dist = sum(abs(d[k]) * size[k] for k in range(3)) - lip
                move = tuple(d[k] * dist for k in range(3))
                speed = float(e.get("speed", 40))
                wait = float(e.get("wait", 3))
                if "health" in e:
                    flags |= MF_SHOOT
                elif "targetname" not in e:
                    flags |= MF_PROXIMITY
            elif cls in ("func_wall", "func_explosive", "func_train", "func_rotating", "func_door_rotating",
                         "func_door_secret", "func_object", "func_killbox", "func_water", "func_conveyor"):
                kind = MV_STATIC
            elif cls == "worldspawn":
                kind = MV_STATIC
            if kind == MV_DOOR and "team" in e:
                teams.setdefault(e["team"], []).append(mi)
            info.append((kind, flags, move, speed, wait, tmin, tmax, name_id(e.get("targetname")),
                         name_id(e.get("target")), e.get("team")))
        # teams: a door's trigger covers its whole team, and they move together
        team_next = [-1] * len(info)
        for members in teams.values():
            for i, mi in enumerate(members):
                team_next[mi] = members[(i + 1) % len(members)]
            lo = [min(b.models[mi]["mins"][k] for mi in members) for k in range(3)]
            hi = [max(b.models[mi]["maxs"][k] for mi in members) for k in range(3)]
            for mi in members:
                k_, f_, mv, sp, wt, _, _, tn, tg, tm = info[mi]
                info[mi] = (k_, f_, mv, sp, wt, lo, hi, tn, tg, tm)
        for mi, (kind, flags, move, speed, wait, tmin, tmax, tn, tg, team) in enumerate(info):
            if kind == MV_DOOR:
                # Think_SpawnDoorTrigger: the doors' box, 60 bigger across
                tmin = [tmin[0] - 60, tmin[1] - 60, tmin[2]]
                tmax = [tmax[0] + 60, tmax[1] + 60, tmax[2]]
            elif kind == MV_BUTTON:
                tmin = [tmin[k] - 1 for k in range(3)]
                tmax = [tmax[k] + 1 for k in range(3)]
            recs.append(struct.pack(">BBhHH3i3i3iii", kind, flags, team_next[mi], tn, tg,
                                    *[fx(x) for x in move], *[fx(x) for x in tmin], *[fx(x) for x in tmax],
                                    fx(speed), fx(wait)))
        return recs

    def preview(self, d):
        os.makedirs(d, exist_ok=True)
        N = self.N
        cols = 32
        rows = (len(self.tile_data) + cols - 1) // cols
        img = Image.new("RGB", (cols * (N + 1), rows * (N + 1)), (255, 0, 255))
        for k, (idx, lut) in enumerate(self.tile_data):
            ox, oy = (k % cols) * (N + 1), (k // cols) * (N + 1)
            for y in range(N):
                for x in range(N):
                    c = lut[idx[y * N + x]]
                    img.putpixel((ox + x, oy + y), ((c & 31) << 3, ((c >> 5) & 31) << 3, ((c >> 10) & 31) << 3))
        img = img.resize((img.width * 2, img.height * 2), Image.NEAREST)
        img.save(os.path.join(d, "tiles.png"))


def rle_zeros(row):
    """Quake's visibility compression: a zero byte is followed by a count of zeros"""
    out = bytearray()
    i = 0
    while i < len(row):
        if row[i]:
            out.append(row[i])
            i += 1
            continue
        j = i
        while j < len(row) and not row[j] and j - i < 255:
            j += 1
        out += bytes((0, j - i))
        i = j
    return bytes(out)


# (src/level.c level_tail: the same order)
TAIL = ["brushsides", "brushes", "leafbrushes", "cells", "marks", "leafs", "nodes"]


class Blob:
    def __init__(self):
        self.buf = bytearray()
        self.sizes = {}

    def add(self, data):
        while len(self.buf) & 31:
            self.buf.append(0)
        ofs = len(self.buf)
        self.buf += data
        self.sizes[ofs] = len(data)
        return ofs

    def data(self):
        return bytes(self.buf)


def main():
    args = [a for a in sys.argv[1:] if not a.startswith("--")]
    os.makedirs(os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "obj", "gen"), exist_ok=True)
    write_class_header(os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "obj", "gen",
                                    "q2classes.h"))
    opts = dict(a[2:].split("=", 1) for a in sys.argv[1:] if a.startswith("--"))
    pak = Pak(args[0])
    bsp = Bsp(pak.read(args[1]))
    baker = Baker(pak, bsp, int(opts.get("res", 2)), float(opts.get("bright", 1.0)))
    baker.lod_min = int(opts.get("lodmin", LOD_MIN))     # (a bigger level, fewer coarse grids: the cart's 4 MB)
    baker.facevis_setting = opts.get("facevis", "24")      # (--facevis=64c: more samples, the leaves' corners)
    baker.portals = int(opts.get("portals", 0))          # (--portals=1: the renderer's test, OPT=-DPORTALS)
    baker.bake(args[2], opts.get("preview"))


if __name__ == "__main__":
    main()
