#!/usr/bin/env python3
"""Bake every model in tools/models.txt that's out of date (tools/bake_md2.py), and write
obj/gen/q2models.h: MDL_<NAME> numbers and the files, in the list's order. Rows marked
"view" (the guns in your hands, loaded one at a time) are numbered apart: VIEW_<NAME>,
VIEW_FILES, and the biggest one's bytes and textures (VIEW_MAX_BYTES, VIEW_MAX_TEX).

    tools/bake_models.py data/pak0.pak cd/
"""
import os
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def main():
    pak, out = sys.argv[1], sys.argv[2]
    rows = []
    for line in open(os.path.join(ROOT, "tools", "models.txt")):
        line = [] if line.lstrip().startswith("#") else line.split()     # (whole-line comments: "#3" is a frame)
        if line:
            rows.append(line)
    me = [os.path.getmtime(os.path.join(ROOT, "tools", f)) for f in ("models.txt", "bake_md2.py", "bake_models.py")]
    for name, file, md2, skins, anims, *opts in rows:
        dst = os.path.join(out, file)
        if os.path.exists(dst) and os.path.getmtime(dst) > max(me):
            continue
        cmd = [sys.executable, os.path.join(ROOT, "tools", "bake_md2.py"), pak, md2, dst, "--skins=" + skins]
        if anims != "-":
            cmd.append("--anims=" + anims)
        cmd += ["--" + o for o in opts if o != "view"]
        subprocess.check_call(cmd)
    gen = os.path.join(ROOT, "obj", "gen")
    os.makedirs(gen, exist_ok=True)
    with open(os.path.join(gen, "q2models.h"), "w") as f:
        f.write("/* generated by tools/bake_models.py from tools/models.txt */\n#ifndef Q2MODELS_H\n#define Q2MODELS_H\n")
        world = [r for r in rows if "view" not in r[5:]]
        view = [r for r in rows if "view" in r[5:]]
        for i, r in enumerate(world):
            f.write("#define MDL_%-12s (%d)\n" % (r[0].upper(), i))
        f.write("#define MDL_COUNT        (%d)\n" % len(world))
        f.write("#define MDL_FILES        %s\n" % ", ".join('"%s"' % r[1] for r in world))
        for i, r in enumerate(view):
            f.write("#define VIEW_%-11s (%d)\n" % (r[0].upper(), i))
        f.write("#define VIEW_COUNT       (%d)\n" % len(view))
        f.write("#define VIEW_FILES       %s\n" % ", ".join('"%s"' % r[1] for r in view))
        vbytes = vtex = 0
        for r in view:
            b = open(os.path.join(out, r[1]), "rb").read()
            vbytes = max(vbytes, len(b))
            vtex = max(vtex, int.from_bytes(b[14:16], "big"))     # (the header's ntex)
        f.write("#define VIEW_MAX_BYTES   (%d)\n" % ((vbytes + 2047) & ~2047))
        f.write("#define VIEW_MAX_TEX     (%d)\n#endif\n" % vtex)


if __name__ == "__main__":
    main()
